import type { SheetData } from "./types";

export const defaultSheet: SheetData = {
  codinome: "",
  nome: "",
  idade: "",
  filosofia: "",
  ancora: "",
  conexao: "",
  experiencia: "",
  primeiraMorte: "",
  anotacoes: "",
  eventosMudanca: 0,
  esperanca: 0,
  pilar: { impeto: 0, resolucao: 0, instinto: 0, cognicao: 0 },
  competencias: {
    Atletismo: 0,
    Eletromecânica: 0,
    Exociência: 0,
    Furtivo: 0,
    História: 0,
    Imanência: 0,
    Influência: 0,
    Investigação: 0,
    Medicina: 0,
    Ofício: 0,
    Primor: 0,
    Propósito: 0,
    Sentidos: 0,
    Sobrevivência: 0
  },
  modelo: "",
  dano: "",
  alcance: "",
  habilidade: "",
  acessorio: "",
  ferramentas: "",
  arquetipo: "",
  tecnicas: "",
  marcas: "",
  idioma: { alvo: "", duracao: "", acoes: "" },
  reducao: 0,
  evasao: 0,
  condicoes: { aflito: false, debilitado: false, imobilizado: false },
  personagemImagem: ""
};
